name: Deploy
on:
  release:
    types: [published, edited]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-env name=VERSION::${{github.event.release.tag_name}}

    - name: Print the version
      run: echo $VERSION

    # This step with error out if the folder already exists. If not, it just prints "Folder does not exist"
    - name: check folder
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: test -d ${{github.event.release.tag_name}} && exit 1 || echo "Folder does not exist"
    
    # The next steps will only run if the version folder does not exist in the server
    - name: Simulate build
      run: |
        mkdir ${VERSION}
        cd ./${VERSION}
        touch script.js

    - name: Copy to gen 01 server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: ${VERSION}
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: './'

    - name: run rsync command in gen 01 server
      id: run_rsync
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script:  ./testing.sh $VERSION

    
