name: CI
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Print the version
      run: echo $VERSION

    - name: Build and deploy the framework
      run: |
        echo commands to build,
        echo deploy your framework ${VERSION}.
