name: Deploy
on:
  release:
    types:
      - published
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}

    - name: Print the version
      run: echo $VERSION

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: whoami

    - name: Build and deploy the framework
      run: |
        echo commands to build,
        echo deploy your framework ${VERSION}.
